codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  range: 90..100
  round: down
  precision: 2
  status:
    project:
      default: off
      unit:
        flags:
          - unit

comment:
  layout: "reach, diff, flags, files"
  behavior: default


flags:
  autocomplete:
    paths:
      - libs/ui/autocomplete/
    carryforward: true
  autofocus:
    paths:
      - libs/ui/autofocus/
    carryforward: true
  button:
    paths:
      - libs/ui/button/
    carryforward: true
  card:
    paths:
      - libs/ui/card/
    carryforward: true
  chart:
    paths:
      - libs/ui/chart/
    carryforward: true
  checkbox:
    paths:
      - libs/ui/checkbox/
    carryforward: true
  chip:
    paths:
      - libs/ui/chip/
    carryforward: true
  cohortDateRange:
    paths:
      - libs/ui/cohort-date-range/
    carryforward: true
  confirmation:
    paths:
      - libs/ui/confirmation/
    carryforward: true
  copy:
    paths:
      - libs/ui/copy/
    carryforward: true
  csvEntry:
    paths:
      - libs/ui/csv-entry/
    carryforward: true
  dateRange:
    paths:
      - libs/ui/date-range/
    carryforward: true
  drawer:
    paths:
      - libs/ui/drawer/
    carryforward: true
  emptyState:
    paths:
      - libs/ui/empty-state/
    carryforward: true
  expansionPanel:
    paths:
      - libs/ui/expansion-panel/
    carryforward: true
  fileUpload:
    paths:
      - libs/ui/file-upload/
    carryforward: true
  formField:
    paths:
      - libs/ui/form-field/
    carryforward: true
  icon:
    paths:
      - libs/ui/icon/
    carryforward: true
  iconButton:
    paths:
      - libs/ui/icon-button/
    carryforward: true
  infoCarousel:
    paths:
      - libs/ui/info-carousel/
    carryforward: true
  input:
    paths:
      - libs/ui/input/
    carryforward: true
  link:
    paths:
      - libs/ui/link/
    carryforward: true
  loadingOverlay:
    paths:
      - libs/ui/loading-overlay/
    carryforward: true
  loginForm:
    paths:
      - libs/ui/login-form/
    carryforward: true
  logo:
    paths:
      - libs/ui/logo/
    carryforward: true
  menu:
    paths:
      - libs/ui/menu/
    carryforward: true
  navigation:
    paths:
      - libs/ui/navigation/
    carryforward: true
  option:
    paths:
      - libs/ui/option/
    carryforward: true
  pageHeader:
    paths:
      - libs/ui/page-header/
    carryforward: true
  paginator:
    paths:
      - libs/ui/paginator/
    carryforward: true
  pipes:
    paths:
      - libs/ui/pipes/
    carryforward: true
  popover:
    paths:
      - libs/ui/popover/
    carryforward: true
  radioGroup:
    paths:
      - libs/ui/radio-group/
    carryforward: true
  scrollbars:
    paths:
      - libs/ui/scrollbars/
    carryforward: true
  seach:
    paths:
      - libs/ui/search/
    carryforward: true
  select:
    paths:
      - libs/ui/select/
    carryforward: true
  selectionList:
    paths:
      - libs/ui/selection-list/
    carryforward: true
  sort:
    paths:
      - libs/ui/sort/
    carryforward: true
  spacing:
    paths:
      - libs/ui/spacing/
    carryforward: true
  styles:
    paths:
      - libs/ui/styles/
    carryforward: true
  table:
    paths:
      - libs/ui/table/
    carryforward: true
  tabs:
    paths:
      - libs/ui/tabs/
    carryforward: true
  toggle:
    paths:
      - libs/ui/toggle/
    carryforward: true
  tooltip:
    paths:
      - libs/ui/tooltip/
    carryforward: true
  utilities:
    paths:
      - libs/ui/utilities/
    carryforward: true
  validationMessages:
    paths:
      - libs/ui/validation-messages/
    carryforward: true
  validators:
    paths:
      - libs/ui/validators/
    carryforward: true
  feUtilities:
    paths:
      - libs/fe-utilities/
    carryforward: true
  feJwt:
    paths:
      - libs/fe-jwt/
    carryforward: true
  feTesting:
    paths:
      - libs/fe-testing/
    carryforward: true

ignore:
  - "coverage"
  - "dist"
  - "docs"
  - "node_modules"
  - "out-tsc"
  - "tooling"
  - "libs/**/*.spec.ts"
  - "libs/**/*.mock.ts"

