// NOTE: Format controlled by GitHub
/* eslint-disable @typescript-eslint/naming-convention, max-len */

export interface GithubIssue {
  created_at: string;
  number: string | number;
  state: string;
  title: string;
  comments: string;
  url: string;
  id: number;
  user: Record<string, any>;
  assignee: Record<string, any>;
  assignees: Record<string, any>[];
  labels: Record<string, any>[];
  [key: string]: any;
}

export interface GithubApi {
  items: GithubIssue[];
  total_count: number;
}

export const MOCK_TABLE_DATA: GithubIssue[] = [
  {
    url: 'https://api.github.com/repos/GetTerminus/terminus-oss/issues/406',
    repository_url: 'https://api.github.com/repos/GetTerminus/terminus-oss',
    labels_url: 'https://api.github.com/repos/GetTerminus/terminus-oss/issues/406/labels{/name}',
    comments_url: 'https://api.github.com/repos/GetTerminus/terminus-oss/issues/406/comments',
    events_url: 'https://api.github.com/repos/GetTerminus/terminus-oss/issues/406/events',
    html_url: 'https://github.com/GetTerminus/terminus-oss/pull/406',
    id: 726767472,
    node_id: 'MDExOlB1bGxSZXF1ZXN0NTA3NzgyNzU0',
    number: '406',
    title: '395 Sidenav - New component',
    user: {
      login: 'benjamincharity',
      id: 270193,
      node_id: 'MDQ6VXNlcjI3MDE5Mw==',
      avatar_url: 'https://avatars3.githubusercontent.com/u/270193?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/benjamincharity',
      html_url: 'https://github.com/benjamincharity',
      followers_url: 'https://api.github.com/users/benjamincharity/followers',
      following_url: 'https://api.github.com/users/benjamincharity/following{/other_user}',
      gists_url: 'https://api.github.com/users/benjamincharity/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/benjamincharity/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/benjamincharity/subscriptions',
      organizations_url: 'https://api.github.com/users/benjamincharity/orgs',
      repos_url: 'https://api.github.com/users/benjamincharity/repos',
      events_url: 'https://api.github.com/users/benjamincharity/events{/privacy}',
      received_events_url: 'https://api.github.com/users/benjamincharity/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [
      {
        id: 2121999325,
        node_id: 'MDU6TGFiZWwyMTIxOTk5MzI1',
        url: 'https://api.github.com/repos/GetTerminus/terminus-oss/labels/PR:%20awaiting%20review',
        name: 'PR: awaiting review',
        color: '923016',
        default: false,
        description: null,
      },
      {
        id: 2242158880,
        node_id: 'MDU6TGFiZWwyMjQyMTU4ODgw',
        url: 'https://api.github.com/repos/GetTerminus/terminus-oss/labels/Size:%20WTF',
        name: 'Size: WTF',
        color: 'ededed',
        default: false,
        description: null,
      },
    ],
    state: 'closed',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: '0',
    created_at: '2020-10-21T18:36:31Z',
    updated_at: '2020-10-29T14:51:22Z',
    closed_at: '2020-10-29T14:51:21Z',
    author_association: 'CONTRIBUTOR',
    active_lock_reason: null,
    draft: false,
    pull_request: {
      url: 'https://api.github.com/repos/GetTerminus/terminus-oss/pulls/406',
      html_url: 'https://github.com/GetTerminus/terminus-oss/pull/406',
      diff_url: 'https://github.com/GetTerminus/terminus-oss/pull/406.diff',
      patch_url: 'https://github.com/GetTerminus/terminus-oss/pull/406.patch',
    },
    body: 'Closes #395 ',
    performed_via_github_app: null,
    score: 1,
  },
  {
    url: 'https://api.github.com/repos/GetTerminus/terminus-oss/issues/405',
    repository_url: 'https://api.github.com/repos/GetTerminus/terminus-oss',
    labels_url: 'https://api.github.com/repos/GetTerminus/terminus-oss/issues/405/labels{/name}',
    comments_url: 'https://api.github.com/repos/GetTerminus/terminus-oss/issues/405/comments',
    events_url: 'https://api.github.com/repos/GetTerminus/terminus-oss/issues/405/events',
    html_url: 'https://github.com/GetTerminus/terminus-oss/issues/405',
    id: 722376174,
    node_id: 'MDU6SXNzdWU3MjIzNzYxNzQ=',
    number: 405,
    title: 'CI: Try to re-enable yarn cache',
    user: {
      login: 'benjamincharity',
      id: 270193,
      node_id: 'MDQ6VXNlcjI3MDE5Mw==',
      avatar_url: 'https://avatars3.githubusercontent.com/u/270193?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/benjamincharity',
      html_url: 'https://github.com/benjamincharity',
      followers_url: 'https://api.github.com/users/benjamincharity/followers',
      following_url: 'https://api.github.com/users/benjamincharity/following{/other_user}',
      gists_url: 'https://api.github.com/users/benjamincharity/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/benjamincharity/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/benjamincharity/subscriptions',
      organizations_url: 'https://api.github.com/users/benjamincharity/orgs',
      repos_url: 'https://api.github.com/users/benjamincharity/repos',
      events_url: 'https://api.github.com/users/benjamincharity/events{/privacy}',
      received_events_url: 'https://api.github.com/users/benjamincharity/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [
      {
        id: 2121999320,
        node_id: 'MDU6TGFiZWwyMTIxOTk5MzIw',
        url: 'https://api.github.com/repos/GetTerminus/terminus-oss/labels/Focus:%20build',
        name: 'Focus: build',
        color: 'bfd4f1',
        default: false,
        description: null,
      },
      {
        id: 2121999339,
        node_id: 'MDU6TGFiZWwyMTIxOTk5MzM5',
        url: 'https://api.github.com/repos/GetTerminus/terminus-oss/labels/Type:%20chore',
        name: 'Type: chore',
        color: 'fef1c2',
        default: false,
        description: null,

      },
    ],
    state: 'closed',
    locked: false,
    assignee: {
      login: 'benjamincharity',
      id: 270193,
      node_id: 'MDQ6VXNlcjI3MDE5Mw==',
      avatar_url: 'https://avatars3.githubusercontent.com/u/270193?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/benjamincharity',
      html_url: 'https://github.com/benjamincharity',
      followers_url: 'https://api.github.com/users/benjamincharity/followers',
      following_url: 'https://api.github.com/users/benjamincharity/following{/other_user}',
      gists_url: 'https://api.github.com/users/benjamincharity/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/benjamincharity/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/benjamincharity/subscriptions',
      organizations_url: 'https://api.github.com/users/benjamincharity/orgs',
      repos_url: 'https://api.github.com/users/benjamincharity/repos',
      events_url: 'https://api.github.com/users/benjamincharity/events{/privacy}',
      received_events_url: 'https://api.github.com/users/benjamincharity/received_events',
      type: 'User',
      site_admin: false,
    },
    assignees: [
      {
        login: 'benjamincharity',
        id: 270193,
        node_id: 'MDQ6VXNlcjI3MDE5Mw==',
        avatar_url: 'https://avatars3.githubusercontent.com/u/270193?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/benjamincharity',
        html_url: 'https://github.com/benjamincharity',
        followers_url: 'https://api.github.com/users/benjamincharity/followers',
        following_url: 'https://api.github.com/users/benjamincharity/following{/other_user}',
        gists_url: 'https://api.github.com/users/benjamincharity/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/benjamincharity/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/benjamincharity/subscriptions',
        organizations_url: 'https://api.github.com/users/benjamincharity/orgs',
        repos_url: 'https://api.github.com/users/benjamincharity/repos',
        events_url: 'https://api.github.com/users/benjamincharity/events{/privacy}',
        received_events_url: 'https://api.github.com/users/benjamincharity/received_events',
        type: 'User',
        site_admin: false,
      },
    ],
    milestone: null,
    comments: '1',
    created_at: '2020-10-15T14:13:34Z',
    updated_at: '2020-10-23T16:07:13Z',
    closed_at: '2020-10-23T16:07:13Z',
    author_association: 'CONTRIBUTOR',
    active_lock_reason: null,
    body: '',
    performed_via_github_app: null,
    score: 1,
  },
  {
    url: 'https://api.github.com/repos/GetTerminus/terminus-oss/issues/404',
    repository_url: 'https://api.github.com/repos/GetTerminus/terminus-oss',
    labels_url: 'https://api.github.com/repos/GetTerminus/terminus-oss/issues/404/labels{/name}',
    comments_url: 'https://api.github.com/repos/GetTerminus/terminus-oss/issues/404/comments',
    events_url: 'https://api.github.com/repos/GetTerminus/terminus-oss/issues/404/events',
    html_url: 'https://github.com/GetTerminus/terminus-oss/pull/404',
    id: 722331642,
    node_id: 'MDExOlB1bGxSZXF1ZXN0NTA0MTAwNTcz',
    number: '404',
    title: 'chore(CI): try new checkout method for pull_requests',
    user: {
      login: 'benjamincharity',
      id: 270193,
      node_id: 'MDQ6VXNlcjI3MDE5Mw==',
      avatar_url: 'https://avatars3.githubusercontent.com/u/270193?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/benjamincharity',
      html_url: 'https://github.com/benjamincharity',
      followers_url: 'https://api.github.com/users/benjamincharity/followers',
      following_url: 'https://api.github.com/users/benjamincharity/following{/other_user}',
      gists_url: 'https://api.github.com/users/benjamincharity/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/benjamincharity/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/benjamincharity/subscriptions',
      organizations_url: 'https://api.github.com/users/benjamincharity/orgs',
      repos_url: 'https://api.github.com/users/benjamincharity/repos',
      events_url: 'https://api.github.com/users/benjamincharity/events{/privacy}',
      received_events_url: 'https://api.github.com/users/benjamincharity/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [
      {
        id: 2121999325,
        node_id: 'MDU6TGFiZWwyMTIxOTk5MzI1',
        url: 'https://api.github.com/repos/GetTerminus/terminus-oss/labels/PR:%20awaiting%20review',
        name: 'PR: awaiting review',
        color: '923016',
        default: false,
        description: null,

      },
    ],
    state: 'closed',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: '0',
    created_at: '2020-10-15T13:21:44Z',
    updated_at: '2020-10-15T14:25:10Z',
    closed_at: '2020-10-15T14:25:09Z',
    author_association: 'CONTRIBUTOR',
    active_lock_reason: null,
    draft: false,
    pull_request: {
      url: 'https://api.github.com/repos/GetTerminus/terminus-oss/pulls/404',
      html_url: 'https://github.com/GetTerminus/terminus-oss/pull/404',
      diff_url: 'https://github.com/GetTerminus/terminus-oss/pull/404.diff',
      patch_url: 'https://github.com/GetTerminus/terminus-oss/pull/404.patch',
    },
    body: '',
    performed_via_github_app: null,
    score: 1,
  },
  {
    url: 'https://api.github.com/repos/GetTerminus/terminus-oss/issues/403',
    repository_url: 'https://api.github.com/repos/GetTerminus/terminus-oss',
    labels_url: 'https://api.github.com/repos/GetTerminus/terminus-oss/issues/403/labels{/name}',
    comments_url: 'https://api.github.com/repos/GetTerminus/terminus-oss/issues/403/comments',
    events_url: 'https://api.github.com/repos/GetTerminus/terminus-oss/issues/403/events',
    html_url: 'https://github.com/GetTerminus/terminus-oss/issues/403',
    id: 721688312,
    node_id: 'MDU6SXNzdWU3MjE2ODgzMTI=',
    number: '403',
    title: 'Table: Test nesting 2 and 3 tables deep',
    user: {
      login: 'benjamincharity',
      id: 270193,
      node_id: 'MDQ6VXNlcjI3MDE5Mw==',
      avatar_url: 'https://avatars3.githubusercontent.com/u/270193?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/benjamincharity',
      html_url: 'https://github.com/benjamincharity',
      followers_url: 'https://api.github.com/users/benjamincharity/followers',
      following_url: 'https://api.github.com/users/benjamincharity/following{/other_user}',
      gists_url: 'https://api.github.com/users/benjamincharity/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/benjamincharity/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/benjamincharity/subscriptions',
      organizations_url: 'https://api.github.com/users/benjamincharity/orgs',
      repos_url: 'https://api.github.com/users/benjamincharity/repos',
      events_url: 'https://api.github.com/users/benjamincharity/events{/privacy}',
      received_events_url: 'https://api.github.com/users/benjamincharity/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [
      {
        id: 2121999302,
        node_id: 'MDU6TGFiZWwyMTIxOTk5MzAy',
        url: 'https://api.github.com/repos/GetTerminus/terminus-oss/labels/Focus:%20component',
        name: 'Focus: component',
        color: 'bfd4f1',
        default: false,
        description: null,
      },
      {
        id: 2121999313,
        node_id: 'MDU6TGFiZWwyMTIxOTk5MzEz',
        url: 'https://api.github.com/repos/GetTerminus/terminus-oss/labels/Needs:%20exploration',
        name: 'Needs: exploration',
        color: 'a23a72',
        default: false,
        description: null,
      },
      {
        id: 2121999339,
        node_id: 'MDU6TGFiZWwyMTIxOTk5MzM5',
        url: 'https://api.github.com/repos/GetTerminus/terminus-oss/labels/Type:%20chore',
        name: 'Type: chore',
        color: 'fef1c2',
        default: false,
        description: null,
      },
    ],
    state: 'open',
    locked: false,
    assignee: {
      login: 'benjamincharity',
      id: 270193,
      node_id: 'MDQ6VXNlcjI3MDE5Mw==',
      avatar_url: 'https://avatars3.githubusercontent.com/u/270193?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/benjamincharity',
      html_url: 'https://github.com/benjamincharity',
      followers_url: 'https://api.github.com/users/benjamincharity/followers',
      following_url: 'https://api.github.com/users/benjamincharity/following{/other_user}',
      gists_url: 'https://api.github.com/users/benjamincharity/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/benjamincharity/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/benjamincharity/subscriptions',
      organizations_url: 'https://api.github.com/users/benjamincharity/orgs',
      repos_url: 'https://api.github.com/users/benjamincharity/repos',
      events_url: 'https://api.github.com/users/benjamincharity/events{/privacy}',
      received_events_url: 'https://api.github.com/users/benjamincharity/received_events',
      type: 'User',
      site_admin: false,
    },
    assignees: [
      {
        login: 'benjamincharity',
        id: 270193,
        node_id: 'MDQ6VXNlcjI3MDE5Mw==',
        avatar_url: 'https://avatars3.githubusercontent.com/u/270193?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/benjamincharity',
        html_url: 'https://github.com/benjamincharity',
        followers_url: 'https://api.github.com/users/benjamincharity/followers',
        following_url: 'https://api.github.com/users/benjamincharity/following{/other_user}',
        gists_url: 'https://api.github.com/users/benjamincharity/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/benjamincharity/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/benjamincharity/subscriptions',
        organizations_url: 'https://api.github.com/users/benjamincharity/orgs',
        repos_url: 'https://api.github.com/users/benjamincharity/repos',
        events_url: 'https://api.github.com/users/benjamincharity/events{/privacy}',
        received_events_url: 'https://api.github.com/users/benjamincharity/received_events',
        type: 'User',
        site_admin: false,
      },
    ],
    milestone: null,
    comments: '0',
    created_at: '2020-10-14T18:33:40Z',
    updated_at: '2020-10-14T18:34:00Z',
    closed_at: null,
    author_association: 'CONTRIBUTOR',
    active_lock_reason: null,
    body: 'Need to test nesting tables inside expandable rows.\n\nCould tackle #398 at the same time',
    performed_via_github_app: null,
    score: 1,
  },
  {
    url: 'https://api.github.com/repos/GetTerminus/terminus-oss/issues/402',
    repository_url: 'https://api.github.com/repos/GetTerminus/terminus-oss',
    labels_url: 'https://api.github.com/repos/GetTerminus/terminus-oss/issues/402/labels{/name}',
    comments_url: 'https://api.github.com/repos/GetTerminus/terminus-oss/issues/402/comments',
    events_url: 'https://api.github.com/repos/GetTerminus/terminus-oss/issues/402/events',
    html_url: 'https://github.com/GetTerminus/terminus-oss/pull/402',
    id: 721670144,
    node_id: 'MDExOlB1bGxSZXF1ZXN0NTAzNTQ4Nzky',
    number: '402',
    title: 'fix(Checkbox): remove unneeded coercion',
    user: { login: 'benjamincharity-dev',
      id: 72091230,
      node_id: 'MDQ6VXNlcjcyMDkxMjMw',
      avatar_url: 'https://avatars0.githubusercontent.com/u/72091230?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/benjamincharity-dev',
      html_url: 'https://github.com/benjamincharity-dev',
      followers_url: 'https://api.github.com/users/benjamincharity-dev/followers',
      following_url: 'https://api.github.com/users/benjamincharity-dev/following{/other_user}',
      gists_url: 'https://api.github.com/users/benjamincharity-dev/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/benjamincharity-dev/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/benjamincharity-dev/subscriptions',
      organizations_url: 'https://api.github.com/users/benjamincharity-dev/orgs',
      repos_url: 'https://api.github.com/users/benjamincharity-dev/repos',
      events_url: 'https://api.github.com/users/benjamincharity-dev/events{/privacy}',
      received_events_url: 'https://api.github.com/users/benjamincharity-dev/received_events',
      type: 'User',
      site_admin: false },
    labels: [],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: '0',
    created_at: '2020-10-14T18:03:56Z',
    updated_at: '2020-10-15T15:59:38Z',
    closed_at: null,
    author_association: 'NONE',
    active_lock_reason: null,
    draft: false,
    pull_request: {
      url: 'https://api.github.com/repos/GetTerminus/terminus-oss/pulls/402',
      html_url: 'https://github.com/GetTerminus/terminus-oss/pull/402',
      diff_url: 'https://github.com/GetTerminus/terminus-oss/pull/402.diff',
      patch_url: 'https://github.com/GetTerminus/terminus-oss/pull/402.patch',
    },
    body: '',
    performed_via_github_app: null,
    score: 1,
  },
  {
    url: 'https://api.github.com/repos/GetTerminus/terminus-oss/issues/401',
    repository_url: 'https://api.github.com/repos/GetTerminus/terminus-oss',
    labels_url: 'https://api.github.com/repos/GetTerminus/terminus-oss/issues/401/labels{/name}',
    comments_url: 'https://api.github.com/repos/GetTerminus/terminus-oss/issues/401/comments',
    events_url: 'https://api.github.com/repos/GetTerminus/terminus-oss/issues/401/events',
    html_url: 'https://github.com/GetTerminus/terminus-oss/pull/401',
    id: 721659438,
    node_id: 'MDExOlB1bGxSZXF1ZXN0NTAzNTQwMTg0',
    number: '401',
    title: 'fix(CI): update fetch for cancel workflow',
    user: {
      login: 'benjamincharity',
      id: 270193,
      node_id: 'MDQ6VXNlcjI3MDE5Mw==',
      avatar_url: 'https://avatars3.githubusercontent.com/u/270193?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/benjamincharity',
      html_url: 'https://github.com/benjamincharity',
      followers_url: 'https://api.github.com/users/benjamincharity/followers',
      following_url: 'https://api.github.com/users/benjamincharity/following{/other_user}',
      gists_url: 'https://api.github.com/users/benjamincharity/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/benjamincharity/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/benjamincharity/subscriptions',
      organizations_url: 'https://api.github.com/users/benjamincharity/orgs',
      repos_url: 'https://api.github.com/users/benjamincharity/repos',
      events_url: 'https://api.github.com/users/benjamincharity/events{/privacy}',
      received_events_url: 'https://api.github.com/users/benjamincharity/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [
      {
        id: 2121999325,
        node_id: 'MDU6TGFiZWwyMTIxOTk5MzI1',
        url: 'https://api.github.com/repos/GetTerminus/terminus-oss/labels/PR:%20awaiting%20review',
        name: 'PR: awaiting review',
        color: '923016',
        default: false,
        description: null,
      },
      {
        id: 2121999334,
        node_id: 'MDU6TGFiZWwyMTIxOTk5MzM0',
        url: 'https://api.github.com/repos/GetTerminus/terminus-oss/labels/Size:%20XS',
        name: 'Size: XS',
        color: 'ededed',
        default: false,
        description: null,
      },
    ],
    state: 'closed',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: '0',
    created_at: '2020-10-14T17:47:14Z',
    updated_at: '2020-10-14T18:00:38Z',
    closed_at: '2020-10-14T18:00:37Z',
    author_association: 'CONTRIBUTOR',
    active_lock_reason: null,
    draft: false,
    pull_request: {
      url: 'https://api.github.com/repos/GetTerminus/terminus-oss/pulls/401',
      html_url: 'https://github.com/GetTerminus/terminus-oss/pull/401',
      diff_url: 'https://github.com/GetTerminus/terminus-oss/pull/401.diff',
      patch_url: 'https://github.com/GetTerminus/terminus-oss/pull/401.patch',
    },
    body: '',
    performed_via_github_app: null,
    score: 1,
  },
  {
    url: 'https://api.github.com/repos/GetTerminus/terminus-oss/issues/400',
    repository_url: 'https://api.github.com/repos/GetTerminus/terminus-oss',
    labels_url: 'https://api.github.com/repos/GetTerminus/terminus-oss/issues/400/labels{/name}',
    comments_url: 'https://api.github.com/repos/GetTerminus/terminus-oss/issues/400/comments',
    events_url: 'https://api.github.com/repos/GetTerminus/terminus-oss/issues/400/events',
    html_url: 'https://github.com/GetTerminus/terminus-oss/pull/400',
    id: 721656974,
    node_id: 'MDExOlB1bGxSZXF1ZXN0NTAzNTM4MjE5',
    number: '400',
    title: 'fix(Checkbox): remove unneeded coercion',
    user: {
      login: 'benjamincharity-dev',
      id: 72091230,
      node_id: 'MDQ6VXNlcjcyMDkxMjMw',
      avatar_url: 'https://avatars0.githubusercontent.com/u/72091230?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/benjamincharity-dev',
      html_url: 'https://github.com/benjamincharity-dev',
      followers_url: 'https://api.github.com/users/benjamincharity-dev/followers',
      following_url: 'https://api.github.com/users/benjamincharity-dev/following{/other_user}',
      gists_url: 'https://api.github.com/users/benjamincharity-dev/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/benjamincharity-dev/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/benjamincharity-dev/subscriptions',
      organizations_url: 'https://api.github.com/users/benjamincharity-dev/orgs',
      repos_url: 'https://api.github.com/users/benjamincharity-dev/repos',
      events_url: 'https://api.github.com/users/benjamincharity-dev/events{/privacy}',
      received_events_url: 'https://api.github.com/users/benjamincharity-dev/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [],
    state: 'closed',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: '0',
    created_at: '2020-10-14T17:43:23Z',
    updated_at: '2020-10-14T17:44:52Z',
    closed_at: '2020-10-14T17:44:52Z',
    author_association: 'NONE',
    active_lock_reason: null,
    draft: false,
    pull_request: {
      url: 'https://api.github.com/repos/GetTerminus/terminus-oss/pulls/400',
      html_url: 'https://github.com/GetTerminus/terminus-oss/pull/400',
      diff_url: 'https://github.com/GetTerminus/terminus-oss/pull/400.diff',
      patch_url: 'https://github.com/GetTerminus/terminus-oss/pull/400.patch',
    },
    body: '',
    performed_via_github_app: null,
    score: 1,
  },
  {
    url: 'https://api.github.com/repos/GetTerminus/terminus-oss/issues/399',
    repository_url: 'https://api.github.com/repos/GetTerminus/terminus-oss',
    labels_url: 'https://api.github.com/repos/GetTerminus/terminus-oss/issues/399/labels{/name}',
    comments_url: 'https://api.github.com/repos/GetTerminus/terminus-oss/issues/399/comments',
    events_url: 'https://api.github.com/repos/GetTerminus/terminus-oss/issues/399/events',
    html_url: 'https://github.com/GetTerminus/terminus-oss/pull/399',
    id: 721626779,
    node_id: 'MDExOlB1bGxSZXF1ZXN0NTAzNTEzNjk0',
    number: '399',
    title: 'chore(CI): migrate away from deprecated GHA command',
    user: {
      login: 'benjamincharity',
      id: 270193,
      node_id: 'MDQ6VXNlcjI3MDE5Mw==',
      avatar_url: 'https://avatars3.githubusercontent.com/u/270193?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/benjamincharity',
      html_url: 'https://github.com/benjamincharity',
      followers_url: 'https://api.github.com/users/benjamincharity/followers',
      following_url: 'https://api.github.com/users/benjamincharity/following{/other_user}',
      gists_url: 'https://api.github.com/users/benjamincharity/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/benjamincharity/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/benjamincharity/subscriptions',
      organizations_url: 'https://api.github.com/users/benjamincharity/orgs',
      repos_url: 'https://api.github.com/users/benjamincharity/repos',
      events_url: 'https://api.github.com/users/benjamincharity/events{/privacy}',
      received_events_url: 'https://api.github.com/users/benjamincharity/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [
      { id: 2121999325,
        node_id: 'MDU6TGFiZWwyMTIxOTk5MzI1',
        url: 'https://api.github.com/repos/GetTerminus/terminus-oss/labels/PR:%20awaiting%20review',
        name: 'PR: awaiting review',
        color: '923016',
        default: false,
        description: null }, { id: 2121999334,
        node_id: 'MDU6TGFiZWwyMTIxOTk5MzM0',
        url: 'https://api.github.com/repos/GetTerminus/terminus-oss/labels/Size:%20XS',
        name: 'Size: XS',
        color: 'ededed',
        default: false,
        description: null },
    ],
    state: 'closed',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: '0',
    created_at: '2020-10-14T16:57:59Z',
    updated_at: '2020-10-14T17:45:04Z',
    closed_at: '2020-10-14T17:45:03Z',
    author_association: 'CONTRIBUTOR',
    active_lock_reason: null,
    draft: false,
    pull_request: {
      url: 'https://api.github.com/repos/GetTerminus/terminus-oss/pulls/399',
      html_url: 'https://github.com/GetTerminus/terminus-oss/pull/399',
      diff_url: 'https://github.com/GetTerminus/terminus-oss/pull/399.diff',
      patch_url: 'https://github.com/GetTerminus/terminus-oss/pull/399.patch',
    },
    body: '',
    performed_via_github_app: null,
    score: 1,
  },
  {
    url: 'https://api.github.com/repos/GetTerminus/terminus-oss/issues/398',
    repository_url: 'https://api.github.com/repos/GetTerminus/terminus-oss',
    labels_url: 'https://api.github.com/repos/GetTerminus/terminus-oss/issues/398/labels{/name}',
    comments_url: 'https://api.github.com/repos/GetTerminus/terminus-oss/issues/398/comments',
    events_url: 'https://api.github.com/repos/GetTerminus/terminus-oss/issues/398/events',
    html_url: 'https://github.com/GetTerminus/terminus-oss/issues/398',
    id: 721611064,
    node_id: 'MDU6SXNzdWU3MjE2MTEwNjQ=',
    number: '398',
    title: 'Table: Change stories to use static data',
    user: {
      login: 'benjamincharity',
      id: 270193,
      node_id: 'MDQ6VXNlcjI3MDE5Mw==',
      avatar_url: 'https://avatars3.githubusercontent.com/u/270193?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/benjamincharity',
      html_url: 'https://github.com/benjamincharity',
      followers_url: 'https://api.github.com/users/benjamincharity/followers',
      following_url: 'https://api.github.com/users/benjamincharity/following{/other_user}',
      gists_url: 'https://api.github.com/users/benjamincharity/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/benjamincharity/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/benjamincharity/subscriptions',
      organizations_url: 'https://api.github.com/users/benjamincharity/orgs',
      repos_url: 'https://api.github.com/users/benjamincharity/repos',
      events_url: 'https://api.github.com/users/benjamincharity/events{/privacy}',
      received_events_url: 'https://api.github.com/users/benjamincharity/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [
      {
        id: 2121999290,
        node_id: 'MDU6TGFiZWwyMTIxOTk5Mjkw',
        url: 'https://api.github.com/repos/GetTerminus/terminus-oss/labels/Focus:%20testing',
        name: 'Focus: testing',
        color: 'bfd4f1',
        default: false,
        description: null,
      },
      {
        id: 2121999339,
        node_id: 'MDU6TGFiZWwyMTIxOTk5MzM5',
        url: 'https://api.github.com/repos/GetTerminus/terminus-oss/labels/Type:%20chore',
        name: 'Type: chore',
        color: 'fef1c2',
        default: false,
        description: null,
      },
    ],
    state: 'closed',
    locked: false,
    assignee: {
      login: 'benjamincharity',
      id: 270193,
      node_id: 'MDQ6VXNlcjI3MDE5Mw==',
      avatar_url: 'https://avatars3.githubusercontent.com/u/270193?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/benjamincharity',
      html_url: 'https://github.com/benjamincharity',
      followers_url: 'https://api.github.com/users/benjamincharity/followers',
      following_url: 'https://api.github.com/users/benjamincharity/following{/other_user}',
      gists_url: 'https://api.github.com/users/benjamincharity/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/benjamincharity/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/benjamincharity/subscriptions',
      organizations_url: 'https://api.github.com/users/benjamincharity/orgs',
      repos_url: 'https://api.github.com/users/benjamincharity/repos',
      events_url: 'https://api.github.com/users/benjamincharity/events{/privacy}',
      received_events_url: 'https://api.github.com/users/benjamincharity/received_events',
      type: 'User',
      site_admin: false,
    },
    assignees: [
      {
        login: 'benjamincharity',
        id: 270193,
        node_id: 'MDQ6VXNlcjI3MDE5Mw==',
        avatar_url: 'https://avatars3.githubusercontent.com/u/270193?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/benjamincharity',
        html_url: 'https://github.com/benjamincharity',
        followers_url: 'https://api.github.com/users/benjamincharity/followers',
        following_url: 'https://api.github.com/users/benjamincharity/following{/other_user}',
        gists_url: 'https://api.github.com/users/benjamincharity/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/benjamincharity/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/benjamincharity/subscriptions',
        organizations_url: 'https://api.github.com/users/benjamincharity/orgs',
        repos_url: 'https://api.github.com/users/benjamincharity/repos',
        events_url: 'https://api.github.com/users/benjamincharity/events{/privacy}',
        received_events_url: 'https://api.github.com/users/benjamincharity/received_events',
        type: 'User',
        site_admin: false,
      },
    ],
    milestone: null,
    comments: '1',
    created_at: '2020-10-14T16:36:19Z',
    updated_at: '2020-10-28T12:35:17Z',
    closed_at: '2020-10-28T12:35:17Z',
    author_association: 'CONTRIBUTOR',
    active_lock_reason: null,
    body: "The changing data triggers regression tests each time even though the component hasn't changed. We should use static data so this is avoided.",
    performed_via_github_app: null,
    score: 1,
  },
  {
    url: 'https://api.github.com/repos/GetTerminus/terminus-oss/issues/397',
    repository_url: 'https://api.github.com/repos/GetTerminus/terminus-oss',
    labels_url: 'https://api.github.com/repos/GetTerminus/terminus-oss/issues/397/labels{/name}',
    comments_url: 'https://api.github.com/repos/GetTerminus/terminus-oss/issues/397/comments',
    events_url: 'https://api.github.com/repos/GetTerminus/terminus-oss/issues/397/events',
    html_url: 'https://github.com/GetTerminus/terminus-oss/pull/397',
    id: 721602345,
    node_id: 'MDExOlB1bGxSZXF1ZXN0NTAzNDkzMDE4',
    number: '397',
    title: 'chore(CI): attempt new checkout and affected code',
    user: {
      login: 'benjamincharity',
      id: 270193,
      node_id: 'MDQ6VXNlcjI3MDE5Mw==',
      avatar_url: 'https://avatars3.githubusercontent.com/u/270193?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/benjamincharity',
      html_url: 'https://github.com/benjamincharity',
      followers_url: 'https://api.github.com/users/benjamincharity/followers',
      following_url: 'https://api.github.com/users/benjamincharity/following{/other_user}',
      gists_url: 'https://api.github.com/users/benjamincharity/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/benjamincharity/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/benjamincharity/subscriptions',
      organizations_url: 'https://api.github.com/users/benjamincharity/orgs',
      repos_url: 'https://api.github.com/users/benjamincharity/repos',
      events_url: 'https://api.github.com/users/benjamincharity/events{/privacy}',
      received_events_url: 'https://api.github.com/users/benjamincharity/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [
      { id: 2121999325,
        node_id: 'MDU6TGFiZWwyMTIxOTk5MzI1',
        url: 'https://api.github.com/repos/GetTerminus/terminus-oss/labels/PR:%20awaiting%20review',
        name: 'PR: awaiting review',
        color: '923016',
        default: false,
        description: null },
      {
        id: 2121999334,
        node_id: 'MDU6TGFiZWwyMTIxOTk5MzM0',
        url: 'https://api.github.com/repos/GetTerminus/terminus-oss/labels/Size:%20XS',
        name: 'Size: XS',
        color: 'ededed',
        default: false,
        description: null,
      },
    ],
    state: 'closed',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: '0',
    created_at: '2020-10-14T16:23:31Z',
    updated_at: '2020-10-14T17:37:06Z',
    closed_at: '2020-10-14T17:37:05Z',
    author_association: 'CONTRIBUTOR',
    active_lock_reason: null,
    draft: false,
    pull_request: {
      url: 'https://api.github.com/repos/GetTerminus/terminus-oss/pulls/397',
      html_url: 'https://github.com/GetTerminus/terminus-oss/pull/397',
      diff_url: 'https://github.com/GetTerminus/terminus-oss/pull/397.diff',
      patch_url: 'https://github.com/GetTerminus/terminus-oss/pull/397.patch',
    },
    body: '',
    performed_via_github_app: null,
    score: 1,
  },
];

export const MOCK_TABLE_RESPONSE: GithubApi = {
  items: MOCK_TABLE_DATA.slice(),
  total_count: MOCK_TABLE_DATA.length,
};
