// export const TOKENS = {
//   animation: {
//     easing: {
//       easeIn: {
//         value: 'cubic-bezier(0.0, 0.0, 0.2, 1)',
//         original: { value: 'cubic-bezier(0.0, 0.0, 0.2, 1)' },
//         name: 'TsAnimationEasingEaseIn',
//         attributes: {
//           category: 'animation',
//           type: 'easing',
//           item: 'easeIn',
//         },
//         path: [
//           'animation',
//           'easing',
//           'easeIn',
//         ],
//       },
//       ease: {
//         value: 'cubic-bezier(0.26, 0.86, 0.44, 0.985)',
//         original: { value: 'cubic-bezier(0.26, 0.86, 0.44, 0.985)' },
//         name: 'TsAnimationEasingEase',
//         attributes: {
//           category: 'animation',
//           type: 'easing',
//           item: 'ease',
//         },
//         path: [
//           'animation',
//           'easing',
//           'ease',
//         ],
//       },
//       easeOut: {
//         value: 'cubic-bezier(0.4, 0.0, 1, 1)',
//         original: { value: 'cubic-bezier(0.4, 0.0, 1, 1)' },
//         name: 'TsAnimationEasingEaseOut',
//         attributes: {
//           category: 'animation',
//           type: 'easing',
//           item: 'easeOut',
//         },
//         path: [
//           'animation',
//           'easing',
//           'easeOut',
//         ],
//       },
//     },
//     time: {
//       duration: {
//         0: {
//           value: 0,
//           original: { value: 0 },
//           name: 'TsAnimationTimeDuration0',
//           attributes: {
//             category: 'animation',
//             type: 'time',
//             item: 'duration',
//             subitem: '0',
//           },
//           path: [
//             'animation',
//             'time',
//             'duration',
//             '0',
//           ],
//         },
//         100: {
//           value: '100ms',
//           original: { value: 100 },
//           name: 'TsAnimationTimeDuration100',
//           attributes: {
//             category: 'animation',
//             type: 'time',
//             item: 'duration',
//             subitem: '100',
//           },
//           path: [
//             'animation',
//             'time',
//             'duration',
//             '100',
//           ],
//         },
//         200: {
//           value: '200ms',
//           original: { value: 200 },
//           name: 'TsAnimationTimeDuration200',
//           attributes: {
//             category: 'animation',
//             type: 'time',
//             item: 'duration',
//             subitem: '200',
//           },
//           path: [
//             'animation',
//             'time',
//             'duration',
//             '200',
//           ],
//         },
//         300: {
//           value: '300ms',
//           original: { value: 300 },
//           name: 'TsAnimationTimeDuration300',
//           attributes: {
//             category: 'animation',
//             type: 'time',
//             item: 'duration',
//             subitem: '300',
//           },
//           path: [
//             'animation',
//             'time',
//             'duration',
//             '300',
//           ],
//         },
//         400: {
//           value: '400ms',
//           original: { value: 400 },
//           name: 'TsAnimationTimeDuration400',
//           attributes: {
//             category: 'animation',
//             type: 'time',
//             item: 'duration',
//             subitem: '400',
//           },
//           path: [
//             'animation',
//             'time',
//             'duration',
//             '400',
//           ],
//         },
//         500: {
//           value: '500ms',
//           original: { value: 500 },
//           name: 'TsAnimationTimeDuration500',
//           attributes: {
//             category: 'animation',
//             type: 'time',
//             item: 'duration',
//             subitem: '500',
//           },
//           path: [
//             'animation',
//             'time',
//             'duration',
//             '500',
//           ],
//         },
//         600: {
//           value: '600ms',
//           original: { value: 600 },
//           name: 'TsAnimationTimeDuration600',
//           attributes: {
//             category: 'animation',
//             type: 'time',
//             item: 'duration',
//             subitem: '600',
//           },
//           path: [
//             'animation',
//             'time',
//             'duration',
//             '600',
//           ],
//         },
//         700: {
//           value: '700ms',
//           original: { value: 700 },
//           name: 'TsAnimationTimeDuration700',
//           attributes: {
//             category: 'animation',
//             type: 'time',
//             item: 'duration',
//             subitem: '700',
//           },
//           path: [
//             'animation',
//             'time',
//             'duration',
//             '700',
//           ],
//         },
//         800: {
//           value: '800ms',
//           original: { value: 800 },
//           name: 'TsAnimationTimeDuration800',
//           attributes: {
//             category: 'animation',
//             type: 'time',
//             item: 'duration',
//             subitem: '800',
//           },
//           path: [
//             'animation',
//             'time',
//             'duration',
//             '800',
//           ],
//         },
//         900: {
//           value: '900ms',
//           original: { value: 900 },
//           name: 'TsAnimationTimeDuration900',
//           attributes: {
//             category: 'animation',
//             type: 'time',
//             item: 'duration',
//             subitem: '900',
//           },
//           path: [
//             'animation',
//             'time',
//             'duration',
//             '900',
//           ],
//         },
//         1000: {
//           value: '1000ms',
//           original: { value: 1000 },
//           name: 'TsAnimationTimeDuration1000',
//           attributes: {
//             category: 'animation',
//             type: 'time',
//             item: 'duration',
//             subitem: '1000',
//           },
//           path: [
//             'animation',
//             'time',
//             'duration',
//             '1000',
//           ],
//         },
//       },
//       delay: {
//         0: {
//           value: 0,
//           original: { value: 0 },
//           name: 'TsAnimationTimeDelay0',
//           attributes: {
//             category: 'animation',
//             type: 'time',
//             item: 'delay',
//             subitem: '0',
//           },
//           path: [
//             'animation',
//             'time',
//             'delay',
//             '0',
//           ],
//         },
//         100: {
//           value: '50ms',
//           original: { value: 50 },
//           name: 'TsAnimationTimeDelay100',
//           attributes: {
//             category: 'animation',
//             type: 'time',
//             item: 'delay',
//             subitem: '100',
//           },
//           path: [
//             'animation',
//             'time',
//             'delay',
//             '100',
//           ],
//         },
//         200: {
//           value: '100ms',
//           original: { value: 100 },
//           name: 'TsAnimationTimeDelay200',
//           attributes: {
//             category: 'animation',
//             type: 'time',
//             item: 'delay',
//             subitem: '200',
//           },
//           path: [
//             'animation',
//             'time',
//             'delay',
//             '200',
//           ],
//         },
//         300: {
//           value: '200ms',
//           original: { value: 200 },
//           name: 'TsAnimationTimeDelay300',
//           attributes: {
//             category: 'animation',
//             type: 'time',
//             item: 'delay',
//             subitem: '300',
//           },
//           path: [
//             'animation',
//             'time',
//             'delay',
//             '300',
//           ],
//         },
//         400: {
//           value: '250ms',
//           original: { value: 250 },
//           name: 'TsAnimationTimeDelay400',
//           attributes: {
//             category: 'animation',
//             type: 'time',
//             item: 'delay',
//             subitem: '400',
//           },
//           path: [
//             'animation',
//             'time',
//             'delay',
//             '400',
//           ],
//         },
//       },
//     },
//   },
//   border: {
//     radius: {
//       base: {
//         value: '3px',
//         original: { value: '3px' },
//         name: 'TsBorderRadiusBase',
//         attributes: {
//           category: 'border',
//           type: 'radius',
//           item: 'base',
//         },
//         path: [
//           'border',
//           'radius',
//           'base',
//         ],
//       },
//     },
//     width: {
//       base: {
//         value: '1px',
//         original: { value: '1px' },
//         name: 'TsBorderWidthBase',
//         attributes: {
//           category: 'border',
//           type: 'width',
//           item: 'base',
//         },
//         path: [
//           'border',
//           'width',
//           'base',
//         ],
//       },
//       circle: {
//         value: '50%',
//         type: 'percent',
//         original: {
//           value: '50%',
//           type: 'percent',
//         },
//         name: 'TsBorderWidthCircle',
//         attributes: {
//           category: 'border',
//           type: 'width',
//           item: 'circle',
//         },
//         path: [
//           'border',
//           'width',
//           'circle',
//         ],
//       },
//     },
//   },
//   color: {
//     base: {
//       white: {
//         value: '#fafafa',
//         original: { value: '#fafafa' },
//         name: 'TsColorBaseWhite',
//         attributes: {
//           category: 'color',
//           type: 'base',
//           item: 'white',
//         },
//         path: [
//           'color',
//           'base',
//           'white',
//         ],
//       },
//       black: {
//         value: '#302d35',
//         original: { value: '#302d35' },
//         name: 'TsColorBaseBlack',
//         attributes: {
//           category: 'color',
//           type: 'base',
//           item: 'black',
//         },
//         path: [
//           'color',
//           'base',
//           'black',
//         ],
//       },
//       palette1: {
//         100: {
//           value: '#1777b6',
//           original: { value: '#1777b6' },
//           name: 'TsColorBasePalette1100',
//           attributes: {
//             category: 'color',
//             type: 'base',
//             item: 'palette1',
//             subitem: '100',
//           },
//           path: [
//             'color',
//             'base',
//             'palette1',
//             '100',
//           ],
//         },
//         300: {
//           value: '#1666b1',
//           original: { value: '#1666b1' },
//           name: 'TsColorBasePalette1300',
//           attributes: {
//             category: 'color',
//             type: 'base',
//             item: 'palette1',
//             subitem: '300',
//           },
//           path: [
//             'color',
//             'base',
//             'palette1',
//             '300',
//           ],
//         },
//         500: {
//           value: '#00538a',
//           original: { value: '#00538a' },
//           name: 'TsColorBasePalette1500',
//           attributes: {
//             category: 'color',
//             type: 'base',
//             item: 'palette1',
//             subitem: '500',
//           },
//           path: [
//             'color',
//             'base',
//             'palette1',
//             '500',
//           ],
//         },
//         700: {
//           value: '#0c4271',
//           original: { value: '#0c4271' },
//           name: 'TsColorBasePalette1700',
//           attributes: {
//             category: 'color',
//             type: 'base',
//             item: 'palette1',
//             subitem: '700',
//           },
//           path: [
//             'color',
//             'base',
//             'palette1',
//             '700',
//           ],
//         },
//         900: {
//           value: '#0a375b',
//           original: { value: '#0a375b' },
//           name: 'TsColorBasePalette1900',
//           attributes: {
//             category: 'color',
//             type: 'base',
//             item: 'palette1',
//             subitem: '900',
//           },
//           path: [
//             'color',
//             'base',
//             'palette1',
//             '900',
//           ],
//         },
//       },
//       palette2: {
//         100: {
//           value: '#55ad69',
//           original: { value: '#55AD69' },
//           name: 'TsColorBasePalette2100',
//           attributes: {
//             category: 'color',
//             type: 'base',
//             item: 'palette2',
//             subitem: '100',
//           },
//           path: [
//             'color',
//             'base',
//             'palette2',
//             '100',
//           ],
//         },
//         300: {
//           value: '#3b9b5c',
//           original: { value: '#3b9b5c' },
//           name: 'TsColorBasePalette2300',
//           attributes: {
//             category: 'color',
//             type: 'base',
//             item: 'palette2',
//             subitem: '300',
//           },
//           path: [
//             'color',
//             'base',
//             'palette2',
//             '300',
//           ],
//         },
//         500: {
//           value: '#2f854d',
//           original: { value: '#2f854d' },
//           name: 'TsColorBasePalette2500',
//           attributes: {
//             category: 'color',
//             type: 'base',
//             item: 'palette2',
//             subitem: '500',
//           },
//           path: [
//             'color',
//             'base',
//             'palette2',
//             '500',
//           ],
//         },
//         700: {
//           value: '#317448',
//           original: { value: '#317448' },
//           name: 'TsColorBasePalette2700',
//           attributes: {
//             category: 'color',
//             type: 'base',
//             item: 'palette2',
//             subitem: '700',
//           },
//           path: [
//             'color',
//             'base',
//             'palette2',
//             '700',
//           ],
//         },
//         900: {
//           value: '#2b673f',
//           original: { value: '#2b673f' },
//           name: 'TsColorBasePalette2900',
//           attributes: {
//             category: 'color',
//             type: 'base',
//             item: 'palette2',
//             subitem: '900',
//           },
//           path: [
//             'color',
//             'base',
//             'palette2',
//             '900',
//           ],
//         },
//       },
//       palette3: {
//         100: {
//           value: '#f9eacb',
//           original: { value: '#F9EACB' },
//           name: 'TsColorBasePalette3100',
//           attributes: {
//             category: 'color',
//             type: 'base',
//             item: 'palette3',
//             subitem: '100',
//           },
//           path: [
//             'color',
//             'base',
//             'palette3',
//             '100',
//           ],
//         },
//         300: {
//           value: '#f4cd86',
//           original: { value: '#F4CD86' },
//           name: 'TsColorBasePalette3300',
//           attributes: {
//             category: 'color',
//             type: 'base',
//             item: 'palette3',
//             subitem: '300',
//           },
//           path: [
//             'color',
//             'base',
//             'palette3',
//             '300',
//           ],
//         },
//         500: {
//           value: '#eeae4d',
//           original: { value: '#EEAE4D' },
//           name: 'TsColorBasePalette3500',
//           attributes: {
//             category: 'color',
//             type: 'base',
//             item: 'palette3',
//             subitem: '500',
//           },
//           path: [
//             'color',
//             'base',
//             'palette3',
//             '500',
//           ],
//         },
//         700: {
//           value: '#cb843e',
//           original: { value: '#CB843E' },
//           name: 'TsColorBasePalette3700',
//           attributes: {
//             category: 'color',
//             type: 'base',
//             item: 'palette3',
//             subitem: '700',
//           },
//           path: [
//             'color',
//             'base',
//             'palette3',
//             '700',
//           ],
//         },
//         900: {
//           value: '#845626',
//           original: { value: '#845626' },
//           name: 'TsColorBasePalette3900',
//           attributes: {
//             category: 'color',
//             type: 'base',
//             item: 'palette3',
//             subitem: '900',
//           },
//           path: [
//             'color',
//             'base',
//             'palette3',
//             '900',
//           ],
//         },
//       },
//       palette4: {
//         100: {
//           value: '#dad4e3',
//           original: { value: '#DAD4E3' },
//           name: 'TsColorBasePalette4100',
//           attributes: {
//             category: 'color',
//             type: 'base',
//             item: 'palette4',
//             subitem: '100',
//           },
//           path: [
//             'color',
//             'base',
//             'palette4',
//             '100',
//           ],
//         },
//         300: {
//           value: '#a295bd',
//           original: { value: '#A295BD' },
//           name: 'TsColorBasePalette4300',
//           attributes: {
//             category: 'color',
//             type: 'base',
//             item: 'palette4',
//             subitem: '300',
//           },
//           path: [
//             'color',
//             'base',
//             'palette4',
//             '300',
//           ],
//         },
//         500: {
//           value: '#7d6ba2',
//           original: { value: '#7D6BA2' },
//           name: 'TsColorBasePalette4500',
//           attributes: {
//             category: 'color',
//             type: 'base',
//             item: 'palette4',
//             subitem: '500',
//           },
//           path: [
//             'color',
//             'base',
//             'palette4',
//             '500',
//           ],
//         },
//         700: {
//           value: '#594288',
//           original: { value: '#594288' },
//           name: 'TsColorBasePalette4700',
//           attributes: {
//             category: 'color',
//             type: 'base',
//             item: 'palette4',
//             subitem: '700',
//           },
//           path: [
//             'color',
//             'base',
//             'palette4',
//             '700',
//           ],
//         },
//         900: {
//           value: '#462e7c',
//           original: { value: '#462E7C' },
//           name: 'TsColorBasePalette4900',
//           attributes: {
//             category: 'color',
//             type: 'base',
//             item: 'palette4',
//             subitem: '900',
//           },
//           path: [
//             'color',
//             'base',
//             'palette4',
//             '900',
//           ],
//         },
//       },
//       palette5: {
//         100: {
//           value: '#bddfed',
//           original: { value: '#BDDFED' },
//           name: 'TsColorBasePalette5100',
//           attributes: {
//             category: 'color',
//             type: 'base',
//             item: 'palette5',
//             subitem: '100',
//           },
//           path: [
//             'color',
//             'base',
//             'palette5',
//             '100',
//           ],
//         },
//         300: {
//           value: '#7fbfdc',
//           original: { value: '#7FBFDC' },
//           name: 'TsColorBasePalette5300',
//           attributes: {
//             category: 'color',
//             type: 'base',
//             item: 'palette5',
//             subitem: '300',
//           },
//           path: [
//             'color',
//             'base',
//             'palette5',
//             '300',
//           ],
//         },
//         500: {
//           value: '#4598c6',
//           original: { value: '#4598C6' },
//           name: 'TsColorBasePalette5500',
//           attributes: {
//             category: 'color',
//             type: 'base',
//             item: 'palette5',
//             subitem: '500',
//           },
//           path: [
//             'color',
//             'base',
//             'palette5',
//             '500',
//           ],
//         },
//         700: {
//           value: '#36799e',
//           original: { value: '#36799E' },
//           name: 'TsColorBasePalette5700',
//           attributes: {
//             category: 'color',
//             type: 'base',
//             item: 'palette5',
//             subitem: '700',
//           },
//           path: [
//             'color',
//             'base',
//             'palette5',
//             '700',
//           ],
//         },
//         900: {
//           value: '#1e4a62',
//           original: { value: '#1E4A62' },
//           name: 'TsColorBasePalette5900',
//           attributes: {
//             category: 'color',
//             type: 'base',
//             item: 'palette5',
//             subitem: '900',
//           },
//           path: [
//             'color',
//             'base',
//             'palette5',
//             '900',
//           ],
//         },
//       },
//       palette6: {
//         100: {
//           value: '#d3b6b0',
//           original: { value: '#D3B6B0' },
//           name: 'TsColorBasePalette6100',
//           attributes: {
//             category: 'color',
//             type: 'base',
//             item: 'palette6',
//             subitem: '100',
//           },
//           path: [
//             'color',
//             'base',
//             'palette6',
//             '100',
//           ],
//         },
//         300: {
//           value: '#d59a8d',
//           original: { value: '#D59A8D' },
//           name: 'TsColorBasePalette6300',
//           attributes: {
//             category: 'color',
//             type: 'base',
//             item: 'palette6',
//             subitem: '300',
//           },
//           path: [
//             'color',
//             'base',
//             'palette6',
//             '300',
//           ],
//         },
//         500: {
//           value: '#bc5c49',
//           original: { value: '#BC5C49' },
//           name: 'TsColorBasePalette6500',
//           attributes: {
//             category: 'color',
//             type: 'base',
//             item: 'palette6',
//             subitem: '500',
//           },
//           path: [
//             'color',
//             'base',
//             'palette6',
//             '500',
//           ],
//         },
//         700: {
//           value: '#913b2c',
//           original: { value: '#913B2C' },
//           name: 'TsColorBasePalette6700',
//           attributes: {
//             category: 'color',
//             type: 'base',
//             item: 'palette6',
//             subitem: '700',
//           },
//           path: [
//             'color',
//             'base',
//             'palette6',
//             '700',
//           ],
//         },
//         900: {
//           value: '#763023',
//           original: { value: '#763023' },
//           name: 'TsColorBasePalette6900',
//           attributes: {
//             category: 'color',
//             type: 'base',
//             item: 'palette6',
//             subitem: '900',
//           },
//           path: [
//             'color',
//             'base',
//             'palette6',
//             '900',
//           ],
//         },
//       },
//       palette7: {
//         100: {
//           value: '#f2f0f7',
//           original: { value: '#f2f0f7' },
//           name: 'TsColorBasePalette7100',
//           attributes: {
//             category: 'color',
//             type: 'base',
//             item: 'palette7',
//             subitem: '100',
//           },
//           path: [
//             'color',
//             'base',
//             'palette7',
//             '100',
//           ],
//         },
//         300: {
//           value: '#cecdd1',
//           original: { value: '#cecdd1' },
//           name: 'TsColorBasePalette7300',
//           attributes: {
//             category: 'color',
//             type: 'base',
//             item: 'palette7',
//             subitem: '300',
//           },
//           path: [
//             'color',
//             'base',
//             'palette7',
//             '300',
//           ],
//         },
//         500: {
//           value: '#999999',
//           original: { value: '#999' },
//           name: 'TsColorBasePalette7500',
//           attributes: {
//             category: 'color',
//             type: 'base',
//             item: 'palette7',
//             subitem: '500',
//           },
//           path: [
//             'color',
//             'base',
//             'palette7',
//             '500',
//           ],
//         },
//         700: {
//           value: '#757575',
//           original: { value: '#757575' },
//           name: 'TsColorBasePalette7700',
//           attributes: {
//             category: 'color',
//             type: 'base',
//             item: 'palette7',
//             subitem: '700',
//           },
//           path: [
//             'color',
//             'base',
//             'palette7',
//             '700',
//           ],
//         },
//         900: {
//           value: '#3e3c43',
//           original: { value: '#3e3c43' },
//           name: 'TsColorBasePalette7900',
//           attributes: {
//             category: 'color',
//             type: 'base',
//             item: 'palette7',
//             subitem: '900',
//           },
//           path: [
//             'color',
//             'base',
//             'palette7',
//             '900',
//           ],
//         },
//       },
//     },
//     brand: {
//       terminus: {
//         blue: {
//           value: '#005589',
//           original: { value: '#005589' },
//           name: 'TsColorBrandTerminusBlue',
//           attributes: {
//             category: 'color',
//             type: 'brand',
//             item: 'terminus',
//             subitem: 'blue',
//           },
//           path: [
//             'color',
//             'brand',
//             'terminus',
//             'blue',
//           ],
//         },
//         blueDark: {
//           value: '#0f2d52',
//           original: { value: '#0f2d52' },
//           name: 'TsColorBrandTerminusBlueDark',
//           attributes: {
//             category: 'color',
//             type: 'brand',
//             item: 'terminus',
//             subitem: 'blueDark',
//           },
//           path: [
//             'color',
//             'brand',
//             'terminus',
//             'blueDark',
//           ],
//         },
//         blueLight: {
//           value: '#005589',
//           original: { value: '#005589' },
//           name: 'TsColorBrandTerminusBlueLight',
//           attributes: {
//             category: 'color',
//             type: 'brand',
//             item: 'terminus',
//             subitem: 'blueLight',
//           },
//           path: [
//             'color',
//             'brand',
//             'terminus',
//             'blueLight',
//           ],
//         },
//         plum: {
//           value: '#4c2683',
//           original: { value: '#4c2683' },
//           name: 'TsColorBrandTerminusPlum',
//           attributes: {
//             category: 'color',
//             type: 'brand',
//             item: 'terminus',
//             subitem: 'plum',
//           },
//           path: [
//             'color',
//             'brand',
//             'terminus',
//             'plum',
//           ],
//         },
//         orange: {
//           value: '#d88219',
//           original: { value: '#d88219' },
//           name: 'TsColorBrandTerminusOrange',
//           attributes: {
//             category: 'color',
//             type: 'brand',
//             item: 'terminus',
//             subitem: 'orange',
//           },
//           path: [
//             'color',
//             'brand',
//             'terminus',
//             'orange',
//           ],
//         },
//         orangeLight: {
//           value: '#fbad18',
//           original: { value: '#fbad18' },
//           name: 'TsColorBrandTerminusOrangeLight',
//           attributes: {
//             category: 'color',
//             type: 'brand',
//             item: 'terminus',
//             subitem: 'orangeLight',
//           },
//           path: [
//             'color',
//             'brand',
//             'terminus',
//             'orangeLight',
//           ],
//         },
//         green: {
//           value: '#97cd78',
//           original: { value: '#97cd78' },
//           name: 'TsColorBrandTerminusGreen',
//           attributes: {
//             category: 'color',
//             type: 'brand',
//             item: 'terminus',
//             subitem: 'green',
//           },
//           path: [
//             'color',
//             'brand',
//             'terminus',
//             'green',
//           ],
//         },
//       },
//       sigstr: {},
//     },
//   },
//   space: {
//     base: {
//       small2: {
//         value: '4px',
//         original: { value: 4 },
//         name: 'TsSpaceBaseSmall2',
//         attributes: {
//           category: 'space',
//           type: 'base',
//           item: 'small2',
//         },
//         path: [
//           'space',
//           'base',
//           'small2',
//         ],
//       },
//       small1: {
//         value: '8px',
//         original: { value: 8 },
//         name: 'TsSpaceBaseSmall1',
//         attributes: {
//           category: 'space',
//           type: 'base',
//           item: 'small1',
//         },
//         path: [
//           'space',
//           'base',
//           'small1',
//         ],
//       },
//       small0: {
//         value: '12px',
//         original: { value: 12 },
//         name: 'TsSpaceBaseSmall0',
//         attributes: {
//           category: 'space',
//           type: 'base',
//           item: 'small0',
//         },
//         path: [
//           'space',
//           'base',
//           'small0',
//         ],
//       },
//       base: {
//         value: '16px',
//         original: { value: 16 },
//         name: 'TsSpaceBaseBase',
//         attributes: {
//           category: 'space',
//           type: 'base',
//           item: 'base',
//         },
//         path: [
//           'space',
//           'base',
//           'base',
//         ],
//       },
//       large0: {
//         value: '24px',
//         original: { value: 24 },
//         name: 'TsSpaceBaseLarge0',
//         attributes: {
//           category: 'space',
//           type: 'base',
//           item: 'large0',
//         },
//         path: [
//           'space',
//           'base',
//           'large0',
//         ],
//       },
//       large1: {
//         value: '32px',
//         original: { value: 32 },
//         name: 'TsSpaceBaseLarge1',
//         attributes: {
//           category: 'space',
//           type: 'base',
//           item: 'large1',
//         },
//         path: [
//           'space',
//           'base',
//           'large1',
//         ],
//       },
//       large2: {
//         value: '40px',
//         original: { value: 40 },
//         name: 'TsSpaceBaseLarge2',
//         attributes: {
//           category: 'space',
//           type: 'base',
//           item: 'large2',
//         },
//         path: [
//           'space',
//           'base',
//           'large2',
//         ],
//       },
//       large3: {
//         value: '48px',
//         original: { value: 48 },
//         name: 'TsSpaceBaseLarge3',
//         attributes: {
//           category: 'space',
//           type: 'base',
//           item: 'large3',
//         },
//         path: [
//           'space',
//           'base',
//           'large3',
//         ],
//       },
//       large4: {
//         value: '56px',
//         original: { value: 56 },
//         name: 'TsSpaceBaseLarge4',
//         attributes: {
//           category: 'space',
//           type: 'base',
//           item: 'large4',
//         },
//         path: [
//           'space',
//           'base',
//           'large4',
//         ],
//       },
//       large5: {
//         value: '72px',
//         original: { value: 72 },
//         name: 'TsSpaceBaseLarge5',
//         attributes: {
//           category: 'space',
//           type: 'base',
//           item: 'large5',
//         },
//         path: [
//           'space',
//           'base',
//           'large5',
//         ],
//       },
//       large6: {
//         value: '96px',
//         original: { value: 96 },
//         name: 'TsSpaceBaseLarge6',
//         attributes: {
//           category: 'space',
//           type: 'base',
//           item: 'large6',
//         },
//         path: [
//           'space',
//           'base',
//           'large6',
//         ],
//       },
//     },
//     inline: {
//       200: {
//         value: '4px',
//         original: { value: '{ space.base.small2.value }' },
//         name: 'TsSpaceInline200',
//         attributes: {
//           category: 'space',
//           type: 'inline',
//           item: '200',
//         },
//         path: [
//           'space',
//           'inline',
//           '200',
//         ],
//       },
//       300: {
//         value: '8px',
//         original: { value: '{ space.base.small1.value }' },
//         name: 'TsSpaceInline300',
//         attributes: {
//           category: 'space',
//           type: 'inline',
//           item: '300',
//         },
//         path: [
//           'space',
//           'inline',
//           '300',
//         ],
//       },
//       400: {
//         value: '12px',
//         original: { value: '{ space.base.small0.value }' },
//         name: 'TsSpaceInline400',
//         attributes: {
//           category: 'space',
//           type: 'inline',
//           item: '400',
//         },
//         path: [
//           'space',
//           'inline',
//           '400',
//         ],
//       },
//       500: {
//         value: '16px',
//         original: { value: '{ space.base.base.value }' },
//         name: 'TsSpaceInline500',
//         attributes: {
//           category: 'space',
//           type: 'inline',
//           item: '500',
//         },
//         path: [
//           'space',
//           'inline',
//           '500',
//         ],
//       },
//       600: {
//         value: '24px',
//         original: { value: '{ space.base.large0.value }' },
//         name: 'TsSpaceInline600',
//         attributes: {
//           category: 'space',
//           type: 'inline',
//           item: '600',
//         },
//         path: [
//           'space',
//           'inline',
//           '600',
//         ],
//       },
//     },
//     inset: {
//       200: {
//         value: '4px',
//         original: { value: '{ space.base.small2.value }' },
//         name: 'TsSpaceInset200',
//         attributes: {
//           category: 'space',
//           type: 'inset',
//           item: '200',
//         },
//         path: [
//           'space',
//           'inset',
//           '200',
//         ],
//       },
//       300: {
//         value: '8px',
//         original: { value: '{ space.base.small1.value }' },
//         name: 'TsSpaceInset300',
//         attributes: {
//           category: 'space',
//           type: 'inset',
//           item: '300',
//         },
//         path: [
//           'space',
//           'inset',
//           '300',
//         ],
//       },
//       400: {
//         value: '12px',
//         original: { value: '{ space.base.small0.value }' },
//         name: 'TsSpaceInset400',
//         attributes: {
//           category: 'space',
//           type: 'inset',
//           item: '400',
//         },
//         path: [
//           'space',
//           'inset',
//           '400',
//         ],
//       },
//       500: {
//         value: '16px',
//         original: { value: '{ space.base.base.value }' },
//         name: 'TsSpaceInset500',
//         attributes: {
//           category: 'space',
//           type: 'inset',
//           item: '500',
//         },
//         path: [
//           'space',
//           'inset',
//           '500',
//         ],
//       },
//       600: {
//         value: '24px',
//         original: { value: '{ space.base.large0.value }' },
//         name: 'TsSpaceInset600',
//         attributes: {
//           category: 'space',
//           type: 'inset',
//           item: '600',
//         },
//         path: [
//           'space',
//           'inset',
//           '600',
//         ],
//       },
//       700: {
//         value: '32px',
//         original: { value: '{ space.base.large1.value }' },
//         name: 'TsSpaceInset700',
//         attributes: {
//           category: 'space',
//           type: 'inset',
//           item: '700',
//         },
//         path: [
//           'space',
//           'inset',
//           '700',
//         ],
//       },
//     },
//     stack: {
//       200: {
//         value: '4px',
//         original: { value: '{ space.base.small2.value }' },
//         name: 'TsSpaceStack200',
//         attributes: {
//           category: 'space',
//           type: 'stack',
//           item: '200',
//         },
//         path: [
//           'space',
//           'stack',
//           '200',
//         ],
//       },
//       300: {
//         value: '8px',
//         original: { value: '{ space.base.small1.value }' },
//         name: 'TsSpaceStack300',
//         attributes: {
//           category: 'space',
//           type: 'stack',
//           item: '300',
//         },
//         path: [
//           'space',
//           'stack',
//           '300',
//         ],
//       },
//       400: {
//         value: '12px',
//         original: { value: '{ space.base.small0.value }' },
//         name: 'TsSpaceStack400',
//         attributes: {
//           category: 'space',
//           type: 'stack',
//           item: '400',
//         },
//         path: [
//           'space',
//           'stack',
//           '400',
//         ],
//       },
//       500: {
//         value: '16px',
//         original: { value: '{ space.base.base.value }' },
//         name: 'TsSpaceStack500',
//         attributes: {
//           category: 'space',
//           type: 'stack',
//           item: '500',
//         },
//         path: [
//           'space',
//           'stack',
//           '500',
//         ],
//       },
//       600: {
//         value: '24px',
//         original: { value: '{ space.base.large0.value }' },
//         name: 'TsSpaceStack600',
//         attributes: {
//           category: 'space',
//           type: 'stack',
//           item: '600',
//         },
//         path: [
//           'space',
//           'stack',
//           '600',
//         ],
//       },
//       700: {
//         value: '32px',
//         original: { value: '{ space.base.large1.value }' },
//         name: 'TsSpaceStack700',
//         attributes: {
//           category: 'space',
//           type: 'stack',
//           item: '700',
//         },
//         path: [
//           'space',
//           'stack',
//           '700',
//         ],
//       },
//       800: {
//         value: '40px',
//         original: { value: '{ space.base.large2.value }' },
//         name: 'TsSpaceStack800',
//         attributes: {
//           category: 'space',
//           type: 'stack',
//           item: '800',
//         },
//         path: [
//           'space',
//           'stack',
//           '800',
//         ],
//       },
//       900: {
//         value: '48px',
//         original: { value: '{ space.base.large3.value }' },
//         name: 'TsSpaceStack900',
//         attributes: {
//           category: 'space',
//           type: 'stack',
//           item: '900',
//         },
//         path: [
//           'space',
//           'stack',
//           '900',
//         ],
//       },
//       1000: {
//         value: '56px',
//         original: { value: '{ space.base.large4.value }' },
//         name: 'TsSpaceStack1000',
//         attributes: {
//           category: 'space',
//           type: 'stack',
//           item: '1000',
//         },
//         path: [
//           'space',
//           'stack',
//           '1000',
//         ],
//       },
//       1100: {
//         value: '72px',
//         original: { value: '{ space.base.large5.value }' },
//         name: 'TsSpaceStack1100',
//         attributes: {
//           category: 'space',
//           type: 'stack',
//           item: '1100',
//         },
//         path: [
//           'space',
//           'stack',
//           '1100',
//         ],
//       },
//       1200: {
//         value: '96px',
//         original: { value: '{ space.base.large6.value }' },
//         name: 'TsSpaceStack1200',
//         attributes: {
//           category: 'space',
//           type: 'stack',
//           item: '1200',
//         },
//         path: [
//           'space',
//           'stack',
//           '1200',
//         ],
//       },
//     },
//   },
//   typography: {
//     family: {
//       base: {
//         roboto: {
//           value: 'roboto',
//           original: { value: 'roboto' },
//           name: 'TsTypographyFamilyBaseRoboto',
//           attributes: {
//             category: 'typography',
//             type: 'family',
//             item: 'base',
//             subitem: 'roboto',
//           },
//           path: [
//             'typography',
//             'family',
//             'base',
//             'roboto',
//           ],
//         },
//         icons: {
//           value: 'materialicons',
//           original: { value: 'materialicons' },
//           name: 'TsTypographyFamilyBaseIcons',
//           attributes: {
//             category: 'typography',
//             type: 'family',
//             item: 'base',
//             subitem: 'icons',
//           },
//           path: [
//             'typography',
//             'family',
//             'base',
//             'icons',
//           ],
//         },
//         monospaced: {
//           value: "'lucida console'",
//           original: { value: "'lucida console'" },
//           name: 'TsTypographyFamilyBaseMonospaced',
//           attributes: {
//             category: 'typography',
//             type: 'family',
//             item: 'base',
//             subitem: 'monospaced',
//           },
//           path: [
//             'typography',
//             'family',
//             'base',
//             'monospaced',
//           ],
//         },
//       },
//     },
//     stack: {
//       base: {
//         roboto: {
//           value: "roboto, 'helvetica neue', helvetica, arial, sans-serif",
//           original: { value: '{typography.family.base.roboto.value}, {typography.stack.base.sansserif.value}' },
//           name: 'TsTypographyStackBaseRoboto',
//           attributes: {
//             category: 'typography',
//             type: 'stack',
//             item: 'base',
//             subitem: 'roboto',
//           },
//           path: [
//             'typography',
//             'stack',
//             'base',
//             'roboto',
//           ],
//         },
//         sansserif: {
//           value: "'helvetica neue', helvetica, arial, sans-serif",
//           original: { value: "'helvetica neue', helvetica, arial, sans-serif" },
//           name: 'TsTypographyStackBaseSansserif',
//           attributes: {
//             category: 'typography',
//             type: 'stack',
//             item: 'base',
//             subitem: 'sansserif',
//           },
//           path: [
//             'typography',
//             'stack',
//             'base',
//             'sansserif',
//           ],
//         },
//         monospaced: {
//           value: "'lucida console', monaco, 'dejavu sans mono', monospace",
//           original: { value: "{typography.family.base.monospaced.value}, monaco, 'dejavu sans mono', monospace" },
//           name: 'TsTypographyStackBaseMonospaced',
//           attributes: {
//             category: 'typography',
//             type: 'stack',
//             item: 'base',
//             subitem: 'monospaced',
//           },
//           path: [
//             'typography',
//             'stack',
//             'base',
//             'monospaced',
//           ],
//         },
//       },
//     },
//     lineHeight: {
//       300: {
//         value: '20px',
//         original: { value: 20 },
//         name: 'TsTypographyLineHeight300',
//         attributes: {
//           category: 'typography',
//           type: 'lineHeight',
//           item: '300',
//         },
//         path: [
//           'typography',
//           'lineHeight',
//           '300',
//         ],
//       },
//       400: {
//         value: '24px',
//         original: { value: 24 },
//         name: 'TsTypographyLineHeight400',
//         attributes: {
//           category: 'typography',
//           type: 'lineHeight',
//           item: '400',
//         },
//         path: [
//           'typography',
//           'lineHeight',
//           '400',
//         ],
//       },
//       500: {
//         value: '32px',
//         original: { value: 32 },
//         name: 'TsTypographyLineHeight500',
//         attributes: {
//           category: 'typography',
//           type: 'lineHeight',
//           item: '500',
//         },
//         path: [
//           'typography',
//           'lineHeight',
//           '500',
//         ],
//       },
//       600: {
//         value: '40px',
//         original: { value: 40 },
//         name: 'TsTypographyLineHeight600',
//         attributes: {
//           category: 'typography',
//           type: 'lineHeight',
//           item: '600',
//         },
//         path: [
//           'typography',
//           'lineHeight',
//           '600',
//         ],
//       },
//       700: {
//         value: '56px',
//         original: { value: 56 },
//         name: 'TsTypographyLineHeight700',
//         attributes: {
//           category: 'typography',
//           type: 'lineHeight',
//           item: '700',
//         },
//         path: [
//           'typography',
//           'lineHeight',
//           '700',
//         ],
//       },
//       800: {
//         value: '64px',
//         original: { value: 64 },
//         name: 'TsTypographyLineHeight800',
//         attributes: {
//           category: 'typography',
//           type: 'lineHeight',
//           item: '800',
//         },
//         path: [
//           'typography',
//           'lineHeight',
//           '800',
//         ],
//       },
//       1000: {
//         value: '112px',
//         original: { value: 112 },
//         name: 'TsTypographyLineHeight1000',
//         attributes: {
//           category: 'typography',
//           type: 'lineHeight',
//           item: '1000',
//         },
//         path: [
//           'typography',
//           'lineHeight',
//           '1000',
//         ],
//       },
//       base: {
//         value: '20px',
//         original: { value: '{typography.lineHeight.300.value}' },
//         name: 'TsTypographyLineHeightBase',
//         attributes: {
//           category: 'typography',
//           type: 'lineHeight',
//           item: 'base',
//         },
//         path: [
//           'typography',
//           'lineHeight',
//           'base',
//         ],
//       },
//     },
//     size: {
//       200: {
//         value: '12px',
//         original: { value: 12 },
//         name: 'TsTypographySize200',
//         attributes: {
//           category: 'typography',
//           type: 'size',
//           item: '200',
//         },
//         path: [
//           'typography',
//           'size',
//           '200',
//         ],
//       },
//       300: {
//         value: '16px',
//         original: { value: 16 },
//         name: 'TsTypographySize300',
//         attributes: {
//           category: 'typography',
//           type: 'size',
//           item: '300',
//         },
//         path: [
//           'typography',
//           'size',
//           '300',
//         ],
//       },
//       400: {
//         value: '18px',
//         original: { value: 18 },
//         name: 'TsTypographySize400',
//         attributes: {
//           category: 'typography',
//           type: 'size',
//           item: '400',
//         },
//         path: [
//           'typography',
//           'size',
//           '400',
//         ],
//       },
//       500: {
//         value: '20px',
//         original: { value: 20 },
//         name: 'TsTypographySize500',
//         attributes: {
//           category: 'typography',
//           type: 'size',
//           item: '500',
//         },
//         path: [
//           'typography',
//           'size',
//           '500',
//         ],
//       },
//       600: {
//         value: '24px',
//         original: { value: 24 },
//         name: 'TsTypographySize600',
//         attributes: {
//           category: 'typography',
//           type: 'size',
//           item: '600',
//         },
//         path: [
//           'typography',
//           'size',
//           '600',
//         ],
//       },
//       700: {
//         value: '34px',
//         original: { value: 34 },
//         name: 'TsTypographySize700',
//         attributes: {
//           category: 'typography',
//           type: 'size',
//           item: '700',
//         },
//         path: [
//           'typography',
//           'size',
//           '700',
//         ],
//       },
//       800: {
//         value: '45px',
//         original: { value: 45 },
//         name: 'TsTypographySize800',
//         attributes: {
//           category: 'typography',
//           type: 'size',
//           item: '800',
//         },
//         path: [
//           'typography',
//           'size',
//           '800',
//         ],
//       },
//       900: {
//         value: '56px',
//         original: { value: 56 },
//         name: 'TsTypographySize900',
//         attributes: {
//           category: 'typography',
//           type: 'size',
//           item: '900',
//         },
//         path: [
//           'typography',
//           'size',
//           '900',
//         ],
//       },
//       1000: {
//         value: '112px',
//         original: { value: 112 },
//         name: 'TsTypographySize1000',
//         attributes: {
//           category: 'typography',
//           type: 'size',
//           item: '1000',
//         },
//         path: [
//           'typography',
//           'size',
//           '1000',
//         ],
//       },
//       base: {
//         value: '16px',
//         original: { value: '{typography.size.300.value}' },
//         name: 'TsTypographySizeBase',
//         attributes: {
//           category: 'typography',
//           type: 'size',
//           item: 'base',
//         },
//         path: [
//           'typography',
//           'size',
//           'base',
//         ],
//       },
//     },
//   },
// };
