name: PR Labeler
on: deployment_status
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: srvaroa/labeler@master
        name: Autolabel PR
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
